server:
  port: 0

production:
  interval: 1000
  storage-capacity: 10

---
spring:
  profiles: prod

production:
  storage-capacity: 10

---
spring:
  profiles: test

production:
  storage-capacity: 5

